/**
 * An `LlmAdapter` whose models generate images instead of conversing.
 *
 * The harness models a model call as a stream of content blocks, and `image` is
 * one of the declared block types, so an image endpoint fits the existing
 * contract without widening it: the adapter yields a single image block and
 * finishes. It emits no tool calls, so the agent loop runs exactly one step and
 * ends the turn -  "generate only, never converse" is a consequence of the
 * stream shape, not an added restriction.
 *
 * The generated bytes are committed through the attachment service before the
 * block is yielded, the same lifecycle a user-uploaded or `read_image` image
 * gets. An `ImageBlock` carries a durable reference, never inline bytes.
 *
 * @module dsh-plugin-image-model/adapter
 */
import { LlmAdapter, LlmError } from "@deepseek-ai/dsh-llm";
import { credentialRef } from "@deepseek-ai/dsh-credentials";
import { requestImage } from "./images-api.js";
import { findSourceImage, modelOptions, resolvePrompt, shouldGenerate } from "./request.js";

/**
 * Nominal context window reported for an image model.
 *
 * An images endpoint has no context window; the field is required by consumers
 * that project usage, so a route may declare one and this is the fallback.
 */
export const DEFAULT_CONTEXT_WINDOW = 4096;

export class ImageModelAdapter extends LlmAdapter {
  /** @type {Map<string, object>} resolved routes by provider id. */
  #routes;
  /** @type {() => object | undefined} late-bound attachment store lookup. */
  #attachments;
  /** @type {(() => object | undefined) | undefined} late-bound credential store lookup. */
  #credentials;
  /** @type {typeof fetch} */
  #fetch;

  /**
   * @param options - routes plus the injected attachment store, credential store, and fetch.
   */
  constructor({ routes, attachments, credentials, fetchImpl = fetch }) {
    super();
    this.#routes = new Map(routes.map((route) => [route.id, route]));
    this.#attachments = attachments;
    this.#credentials = credentials;
    this.#fetch = fetchImpl;
  }

  /**
   * Replace the served routes in place.
   *
   * The settings panel changes routes while the process runs. The registration
   * handle replaces the route *set* atomically, and this keeps the adapter's own
   * view in step; swapping one map is a single assignment, so no in-flight call
   * can observe a half-updated table.
   *
   * @param routes - the complete next route list.
   */
  setRoutes(routes) {
    this.#routes = new Map(routes.map((route) => [route.id, route]));
  }

  /** Every provider id this adapter currently serves. */
  routeIds() {
    return [...this.#routes.keys()];
  }

  /** Resolve one configured route or fail with a stable code. */
  #route(provider) {
    const route = this.#routes.get(provider);
    if (route === undefined) {
      throw new LlmError(`provider "${provider}" is not configured for image generation`, "NO_ADAPTER");
    }
    return route;
  }

  /** Find the declared model entry, if the deployment listed it. */
  #model(route, model) {
    return route.models.find((entry) => entry.id === model);
  }

  /**
   * Modalities an image route accepts as input. `image` is declared only when
   * the route can edit, because that is the only path that consumes one.
   */
  #inputModalities(route) {
    return route.edits ? ["text", "image"] : ["text"];
  }

  providerInfo(provider) {
    const route = this.#route(provider);
    return { id: provider, name: route.name };
  }

  async listModels(provider) {
    const route = this.#route(provider);
    return route.models.map((model) => ({
      provider,
      id: model.id,
      name: model.name,
      description: model.description ?? "Image generation; this route returns an image and cannot hold a conversation.",
      inputModalities: this.#inputModalities(route),
    }));
  }

  async resolveModel(provider, model) {
    const route = this.#route(provider);
    const declared = this.#model(route, model);
    return {
      provider,
      id: model,
      name: declared?.name ?? model,
      description: declared?.description ?? "Image generation; this route returns an image and cannot hold a conversation.",
      inputModalities: this.#inputModalities(route),
      context: { contextWindow: route.contextWindow },
    };
  }

  /**
   * Resolve the credential for one route at call time.
   *
   * Resolution goes through the host credential store, which already layers the
   * environment with its own storage - so a reference such as `OPENAI_API_KEY`
   * works whether the value came from the service environment or from a key the
   * settings panel saved. Where no credential service is mounted, the
   * environment is read directly so the plugin still works standalone.
   *
   * Read per call rather than at registration, so a corrected key takes effect
   * without a restart and a missing one fails the request with a stable code
   * instead of hiding the provider.
   */
  async #apiKey(route) {
    const ref = route.apiKeyRef;
    if (ref === undefined) return undefined;
    const store = this.#credentials?.();
    if (store !== undefined) {
      const resolved = await store.resolve(credentialRef(ref));
      const value = typeof resolved?.value === "string" ? resolved.value.trim() : "";
      if (value !== "") return value;
    } else {
      const value = process.env[ref];
      if (typeof value === "string" && value.trim() !== "") return value.trim();
    }
    throw new LlmError(
      `image provider "${route.id}" needs the credential ${ref}, which is unset or empty`,
      "MISSING_CREDENTIAL",
    );
  }

  /** Load the bytes of the image being refined. */
  async #loadSource(reference, signal) {
    const attachments = this.#attachments();
    if (attachments === undefined) {
      throw new LlmError("no attachment service is mounted, so the previous image cannot be read", "INVARIANT");
    }
    const stored = await attachments.readImage(reference, signal);
    return {
      data: stored.data,
      mediaType: stored.ref.mediaType,
      ...stored.ref.name === undefined ? {} : { name: stored.ref.name },
    };
  }

  /** Commit generated bytes and return the durable reference an ImageBlock needs. */
  async #commit(image, prompt) {
    const attachments = this.#attachments();
    if (attachments === undefined) {
      throw new LlmError("no attachment service is mounted, so the image cannot be stored", "INVARIANT");
    }
    try {
      return await attachments.saveImage({
        data: image.data,
        mediaType: image.mediaType,
        name: fileNameFor(prompt, image.mediaType),
      });
    } catch (error) {
      throw admissionFailure(error, image, attachments.imageLimits);
    }
  }

  async *stream(options) {
    const route = this.#route(options.provider);
    // An auxiliary consumer reusing this session's route wants text, not a
    // picture. Refuse before the credential check so the failure is free: the
    // session-title generator runs on every new session, and each accepted call
    // would be a billed image nobody asked for. The refusal is deliberately
    // non-retryable, and its callers already tolerate a failed call.
    if (!shouldGenerate(options.purpose)) {
      throw new LlmError(
        `"${options.model}" only generates images, so it cannot answer a ${options.purpose} request; ` +
          "configure a text model for that purpose",
        "INVALID_REQUEST",
      );
    }
    const apiKey = await this.#apiKey(route);
    const prompt = resolvePrompt(options.messages);
    if (prompt === "") {
      throw new LlmError(
        "an image request needs a text prompt; describe the image you want",
        "INVALID_REQUEST",
      );
    }

    const sourceRef = route.edits ? findSourceImage(options.messages) : undefined;
    const image = sourceRef === undefined ? undefined : await this.#loadSource(sourceRef, options.signal);
    const declared = this.#model(route, options.model);

    const result = await requestImage(
      { baseURL: route.baseURL, apiKey },
      {
        model: options.model,
        prompt,
        options: modelOptions(declared, image !== undefined),
        ...image === undefined ? {} : { image },
      },
      options.signal,
      this.#fetch,
    );

    const attachment = await this.#commit(result, prompt);

    // A revised prompt is the provider telling the user what it actually drew,
    // so it is surfaced as text beside the image rather than dropped.
    let index = 0;
    if (result.revisedPrompt !== undefined) {
      yield { type: "block-start", index, blockType: "text" };
      yield { type: "block-end", index, block: { type: "text", text: result.revisedPrompt } };
      index += 1;
    }
    yield { type: "block-start", index, blockType: "image" };
    yield { type: "block-end", index, block: { type: "image", attachment } };

    const usage = normalizeUsage(result.usage);
    if (usage !== undefined) yield { type: "usage", usage };
    yield { type: "finish", reason: { kind: "stop" } };
  }
}

/**
 * Rewrite an attachment-admission refusal into advice about the request that
 * caused it.
 *
 * The store enforces real bounds -  by default 2000 px per side and 3.5 MiB
 * encoded -  and a generated image is the one image the user did not choose the
 * shape of. A bare "Image exceeds the configured byte limit." would leave them
 * guessing, while the fix is always a declared model option, so the limit, the
 * actual value, and the option to change are reported together.
 *
 * Matching is on the store's stable `code`, not its message text, and an
 * unrecognized error is returned untouched.
 *
 * @param error - the error thrown by `saveImage`.
 * @param image - the image that was refused.
 * @param limits - the store's advertised limits, when available.
 * @returns the error to surface.
 */
export function admissionFailure(error, image, limits) {
  const code = typeof error?.code === "string" ? error.code : "";
  const bytes = image?.data?.length ?? 0;
  switch (code) {
    case "IMAGE_TOO_LARGE":
      return new LlmError(
        `the generated image is ${bytes} bytes, over this deployment's ${limits?.maxImageBytes ?? "configured"}-byte limit; ` +
          "declare a smaller size, or outputFormat: jpeg (or webp) so the encode is smaller",
        "INVALID_RESPONSE",
        { cause: error },
      );
    case "IMAGE_DIMENSION_TOO_LARGE":
      return new LlmError(
        `the generated image has a side longer than this deployment's ${limits?.maxImageDimension ?? "configured"}px limit; ` +
          "declare a smaller size for this model",
        "INVALID_RESPONSE",
        { cause: error },
      );
    case "IMAGE_TOO_MANY_PIXELS":
      return new LlmError(
        `the generated image exceeds this deployment's ${limits?.maxImagePixels ?? "configured"}-pixel decoded-size limit; ` +
          "declare a smaller size for this model",
        "INVALID_RESPONSE",
        { cause: error },
      );
    case "IMAGE_TYPE_MISMATCH":
      return new LlmError(
        `the image endpoint returned bytes that do not match their ${image?.mediaType ?? "detected"} signature`,
        "INVALID_RESPONSE",
        { cause: error },
      );
    default:
      return error;
  }
}

/**
 * Map provider image usage onto harness token accounting.
 *
 * Reported only when the provider reports it. Synthesizing counts would put
 * invented numbers into the context meter, which is worse than a blank.
 *
 * @param usage - the provider usage object, if any.
 * @returns harness token usage, or undefined.
 */
export function normalizeUsage(usage) {
  if (usage === undefined || usage === null) return undefined;
  const input = usage.input_tokens ?? usage.prompt_tokens;
  const output = usage.output_tokens ?? usage.completion_tokens;
  const inputTokens = Number.isSafeInteger(input) && input >= 0 ? input : 0;
  const outputTokens = Number.isSafeInteger(output) && output >= 0 ? output : 0;
  if (inputTokens === 0 && outputTokens === 0) return undefined;
  return { inputTokens, outputTokens };
}

/**
 * Derive a display name for the stored attachment from the prompt.
 *
 * The name is display metadata and is never interpreted as a path, but it is
 * still reduced to a safe slug so it cannot look like one.
 *
 * @param prompt - the prompt that produced the image.
 * @param mediaType - the detected media type, used for the extension.
 * @returns a bounded file name.
 */
export function fileNameFor(prompt, mediaType) {
  const extension = mediaType === "image/jpeg" ? "jpg" : mediaType.slice("image/".length);
  const slug = prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return `${slug === "" ? "image" : slug}.${extension}`;
}
